require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2

Rails:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  Enabled: true

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter
  Enabled: true

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space
  Enabled: true

Layout/SpaceInsideParens:
  EnforcedStyle: no_space
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  Enabled: true

Naming/MethodName:
  EnforcedStyle: snake_case
  Enabled: true

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Style/AccessModifierDeclarations:
  EnforcedStyle: group
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition
  Enabled: true

Style/For:
  EnforcedStyle: each
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  Enabled: true

Style/MissingElse:
  EnforcedStyle: case
  Enabled: true

Style/Next:
  EnforcedStyle: skip_modifier_ifs
  Enabled: true

Style/PreferredHashMethods:
  EnforcedStyle: short
  Enabled: true

# Checks if uses of quotes match the configured preference.
Style/StringLiterals:
  Enabled: false

# Checks if uses of quotes inside expressions in interpolated strings match the
# configured preference.
Style/StringLiteralsInInterpolation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: percent
  Enabled: true

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
  
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table
  EnforcedLastArgumentHashStyle: always_ignore

Metrics/AbcSize:
  Max: 200

Metrics/BlockLength:
  Max: 100

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 600

Metrics/ModuleLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 100

Metrics/ParameterLists:
  Max: 15

Layout/LineLength:
  Max: 450
