AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.5
  
Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 100

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 60

Metrics/ParameterLists:
  Max: 10

Metrics/LineLength:
  Max: 450

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: case
  IndentOneStep: true

